package com.example.xchat.activity.extention

import com.example.xchat.R

fun fillLanguages(): ArrayList<LanguageItem> {
    val list = ArrayList<LanguageItem>()

    list.add(LanguageItem(R.drawable.ic_english_flag, "en"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "hi"))
    list.add(LanguageItem(R.drawable.ic_spain_flag, "es"))
    list.add(LanguageItem(R.drawable.ic_german_flag, "fr"))
    list.add(LanguageItem(R.drawable.ic_arabic_flag, "ar"))
    list.add(LanguageItem(R.drawable.ic_bengali_flag, "bn"))
    list.add(LanguageItem(R.drawable.ic_portuguese_flag, "pt"))
    list.add(LanguageItem(R.drawable.ic_russian_flag, "ru"))
    list.add(LanguageItem(R.drawable.ic_urdu_flag, "ur"))
    list.add(LanguageItem(R.drawable.ic_indonesian_flag, "id"))
    list.add(LanguageItem(R.drawable.ic_french_flag, "de"))
    list.add(LanguageItem(R.drawable.ic_japan_flag, "ja"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "mr"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "te"))
    list.add(LanguageItem(R.drawable.ic_turkey_flag, "tr"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "ta"))
    list.add(LanguageItem(R.drawable.ic_korean_flag, "ko"))
    list.add(LanguageItem(R.drawable.ic_philippines_flag, "tl"))
    list.add(LanguageItem(R.drawable.ic_italy_flag, "it"))
    list.add(LanguageItem(R.drawable.ic_polish_flag, "pl"))
    list.add(LanguageItem(R.drawable.ic_ukraine_flag, "uk"))
    list.add(LanguageItem(R.drawable.ic_azerbaijan_flag, "az"))
    list.add(LanguageItem(R.drawable.ic_dutch_flag, "nl"))
    list.add(LanguageItem(R.drawable.ic_romanian_flag, "ro"))
    list.add(LanguageItem(R.drawable.ic_greek_flag, "el"))
    list.add(LanguageItem(R.drawable.ic_czech_flag, "cs"))
    list.add(LanguageItem(R.drawable.ic_hebrew_flag, "iw")) // Android uses "iw"
    list.add(LanguageItem(R.drawable.ic_bulgarian_flag, "bg"))
    list.add(LanguageItem(R.drawable.ic_albania_flag, "sq"))
    list.add(LanguageItem(R.drawable.ic_kazakhstan_flag, "kk"))
    list.add(LanguageItem(R.drawable.ic_serbia_flag, "sr"))
    list.add(LanguageItem(R.drawable.ic_hungary_flag, "hu"))
    list.add(LanguageItem(R.drawable.ic_malaysia_flag, "ms"))
    list.add(LanguageItem(R.drawable.ic_sweden_flag, "sv"))
    list.add(LanguageItem(R.drawable.ic_uzbekistan_flag, "uz"))
    list.add(LanguageItem(R.drawable.ic_iran_flag, "fa"))
    list.add(LanguageItem(R.drawable.ic_china_flag, "zh"))
    list.add(LanguageItem(R.drawable.ic_vietnam_flag, "vi"))
    list.add(LanguageItem(R.drawable.ic_slovakia_flag, "sk"))
    list.add(LanguageItem(R.drawable.ic_denmark_flag, "da"))
    list.add(LanguageItem(R.drawable.ic_croatia_flag, "hr"))
    list.add(LanguageItem(R.drawable.ic_slovenia_flag, "sl"))
    list.add(LanguageItem(R.drawable.ic_spain_flag, "ca"))
    list.add(LanguageItem(R.drawable.ic_thailand_flag, "th"))
    list.add(LanguageItem(R.drawable.ic_norway_flag, "no"))
    list.add(LanguageItem(R.drawable.ic_finland_flag, "fi"))
    list.add(LanguageItem(R.drawable.ic_cambodia_flag, "km"))
    list.add(LanguageItem(R.drawable.ic_myanmar_flag, "my"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "gu"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "kn"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "or"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "ml"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "pa"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "as"))
    list.add(LanguageItem(R.drawable.ic_india_flag, "mai"))

    //list.sortBy { it.languageName }
    return list
}